### ISSUE TITLE
Need xdai archival node for testnets

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/provider-proxy#5]
We currently use a Pocket Network endpoint, which is already at 50% capacity during light testing sessions.

Thus we need a solution for larger testnets.

### Options

1. Increase stake on Pocket to get more capacity
2. Get another "unlimited" endpoint somewhere else
3. Run own endpoint

**Comment by 0xjjpa** [comment]
@tolbrino Pinged @Jaguaras to add you in our private discord channel with the Pocket Network team

**Comment by tolbrino** [comment]
We moved to an Ankr endpoint for now.
